
# Site settings

url: "https://jd-wheaton.github.io"
baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

author: "JD Wheaton"
lang: "en"
title: "[ JD Wheaton ]"
favicon: "/img/favicon.ico"
description: "Website of author"
keywords: "wheaton, joe, joseph, jd, personal, jekyll, theme"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "/img/croc-bg_edited.jpg"
me-img: "https://www.gravatar.com/avatar/d774e223781f9fe2c91a27f5bcb320c5?s=500"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False	# Shuffle the lines.
loop: True
loop-count:	1 # Set False for infinite loop, or set any number for finite loop.
type-speed:	40		# Default 10
start-delay: 200	# Default 200
delete-delay: 7500	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "So far as the theories of mathematics are about reality, they are not certain; so far as they are certain, they are not about reality. -A. Einstein"

me-img: "https://www.gravatar.com/avatar/d774e223781f9fe2c91a27f5bcb320c5?s=500"

##############################
# Color the browser elements #
##############################

color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "jd-wheaton-github-io"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/crocs.jpg"
    date: "2014 to 15 - Crocs"
    description: "Systems Architect"
  - image: "/img/timeline/glcomp.png"
    date: "2014 - GLC"
    description: "Network Consultant"
  - image: "/img/timeline/glc.jpg"
    date: "2012 to 14 - GLC"
    description: "Network Engineer"
  - image: "/img/timeline/ge.jpg"
    date: "2008 to 12 - GE TSG"
    description: "Network Engineer III"
  - image: "/img/timeline/csc.png"
    date: "2004 to 08 - CSC"
    description: "Network Engineer III"
  - image: "/img/timeline/iserv.png"
    date: "2001 to 04 - Iserv"
    description: "Senior Network Engineer"
  - image: "/img/timeline/entre.jpg"
    date: "1999 to 01 - Entre"
    description: "Network Engineer"
  - image: "/img/timeline/gateway.jpg"
    date: "1998 to 99 - Gateway"
    description: "Network Technician"
  - image: "/img/timeline/intel_p75.jpg"
    date: "1994 to 98 - ECS"
    description: "Network Technician"

# First image of the Career timeline

timeline-img: "/img/timeline/basic.png"

###########
# Contact #
###########

################
# Author Blurb #
################

author_blurb: "jdwheaton lives in Pure Michigan, in his spare time, he enjoys drinking tea, reading history books, and learning."
author_blurb_image: "https://www.gravatar.com/avatar/d774e223781f9fe2c91a27f5bcb320c5?s=500"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/jd-wheaton/jd-wheaton.github.io"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: jdwheaton
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  # Blog: 'blog'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
