
# Site settings

url: "http://jd-wheaton.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

#############
# HTML Head #
#############

author: "Joe Wheaton"
lang: "en"
title: "{ Joe Wheaton }"
favicon: "/img/favicon.ico"
description: "Blog and website of Joe Wheaton, blogging for self. Opinions expressed are ludicrous."
keywords: "wheaton, joe, personal, jekyll, theme"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/croc-bg.jpg"
me-img: "/img/JNCIA.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: False
shuffle: False	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Not everything that counts can be counted, and not everything that can be counted counts."
  - text: "If you want to live a happy life, tie it to a goal, not to people or objects."
  - text: "-- Albert Einstein"

########
# Blog #
########

post-preview-words: 128

paginate: 5

fb-share: False
twitter-share: False
reddit-share: False
disqus-shortname: ""

###############
# Life Events #
###############

events:
  - image: "/img/career/crocs.jpg"
    date: "2014 to 2015 - Crocs Casino and Resort, Jaco, Punterenas, Costa Rica"
    description: "Systems Architect - SME R/S, FW, WIFI, AUTOMATION, INFOSEC, GAMING, HOSPITALITY"
  - image: "/img/career/glcomp.png"
    date: "2014 - Great Lakes Computer"
    description: "Network Consultant - SME R/S, FW, WIFI, AUTOMATION, INFOSEC"
  - image: "/img/career/glc.jpg"
    date: "2012 to 2014 - Gun Lake Casino"
    description: "Principle Network Engineer - SME R/S, FW, WIFI, AUTOMATION, INFOSEC, GAMING"
  - image: "/img/career/ge.jpg"
    date: "2008 to 2012 - General Electric / Cincinatti Bell"
    description: "Network Engineer III - SME R/S, FW, WIFI, INFOSEC"
  - image: "/img/career/csc.png"
    date: "2004 to 2008 - CSC"
    description: "Network Engineer III - SME HEALTH CARE INFOSYS, R/S, FW, WIFI, INFOSEC, ARIAL/UNDERGROUND FIBER"
  - image: "/img/career/iserv.png"
    date: "2001 to 2004 - Iserv"
    description: "Head of Network Engineering - SME R/S, PEERING, CONTRACTS, ARIAL/UNDERGROUND FIBER"
  - image: "/img/career/entre.jpg"
    date: "1999 to 2001 - Entre"
    description: "Network Engineer - SME R/S, FW"
  - image: "/img/career/gateway.jpg"
    date: "1998 to 1999 - Gateway"
    description: "Network Technician"
  - image: "/img/career/intel_p75.jpg"
    date: "1994 to 1998 - ECS"
    description: "IT Technician"

# First image of the Career timeline
career-img: "/img/career/basic.png"
date: "1994"
description: "A network adventurer was born early spring 1994 the day I installed Slackware 1.0 and OS2 Warp 4.0 Server, the rest is history."

##################
# Contact layout #
##################

email: "jd.wheaton@outlook.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "http://facebook.com/"
  - title: "twitter"
    url: "http://twitter.com/"
  - title: "youtube"
    url: "http://youtube.com/"
  - title: "github"
    url: "https://github.com/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  # Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
